-- Basic config
require "config.options"
require "config.highlights"
-- require "config.colors"
require "config.keymaps"
require "config.plugins"

-- Plugins config
require "plugins.neosolarized"
require "plugins.lualine"
require "plugins.lspconfig"
require "plugins.lspkind"
require "plugins.cmp"
require "plugins.treesiter"
require "plugins.autopairs"
require "plugins.autotag"
require "plugins.telescope"
require "plugins.bufferline"
require "plugins.colorizer"
require "plugins.lspsaga"
require "plugins.nulls"
require "plugins.gitsigns"
require "plugins.git"
require "plugins.mason"
